#include <stdint.h>

enum {
	UTF8_GRAPHEME_BREAK_OTHER,
	UTF8_GRAPHEME_BREAK_CR,
	UTF8_GRAPHEME_BREAK_LF,
	UTF8_GRAPHEME_BREAK_CONTROL,
	UTF8_GRAPHEME_BREAK_EXTEND,
	UTF8_GRAPHEME_BREAK_REGIONAL_INDICATOR,
	UTF8_GRAPHEME_BREAK_PREPEND,
	UTF8_GRAPHEME_BREAK_SPACINGMARK,
	UTF8_GRAPHEME_BREAK_L,
	UTF8_GRAPHEME_BREAK_V,
	UTF8_GRAPHEME_BREAK_T,
	UTF8_GRAPHEME_BREAK_LV,
	UTF8_GRAPHEME_BREAK_LVT,
};

struct utf8data {
	uint32_t lower;
	uint32_t upper;
	uint8_t width;
	uint8_t grapheme_break;
};

struct utf8data utf8data[] = {
#include "utf8data.c"
};
